on: push

jobs:

  render-book:
  
    runs-on: windows-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv
      
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) {
            install.packages("renv")
          }
          renv::restore()
      
      - name: Render book
        run: Rscript -e 'bookdown::render_book()'
      
      - name: Commit and push results
        run: |
          git config --local user.email "oelschlaeger.lennart@gmail.com"
          git config --local user.name "Lennart Oelschlaeger"
          git add .
          git commit -m 'Rendered book :books:' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
